// <auto-generated>
// Rewired Constants
// This list was generated on 2/26/2020 10:53:56 AM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace TAPI.Inputs {
    public static partial class Action {
        // Default
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Horizontal")]
        public const int Horizontal = 19;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Vertical")]
        public const int Vertical = 20;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Submit")]
        public const int Submit = 21;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Cancel")]
        public const int Cancel = 22;
        // Player
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Movement X")]
        public const int Movement_X = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Movement Y")]
        public const int Movement_Y = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Camera X")]
        public const int Camera_X = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Camera Y")]
        public const int Camera_Y = 15;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Lock-On")]
        public const int Lock_On = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Interact")]
        public const int Interact = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Bullet")]
        public const int Bullet = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Attack")]
        public const int Attack = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Float")]
        public const int Float = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Dash")]
        public const int Dash = 17;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Jump")]
        public const int Jump = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Taunt")]
        public const int Taunt = 26;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Spell Card 1")]
        public const int Spell_Card_1 = 27;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Spell Card 3")]
        public const int Spell_Card_2 = 28;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Spell Card 3")]
        public const int Spell_Card_3 = 29;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Spell Card 4")]
        public const int Spell_Card_4 = 30;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int UI = 1;
        public const int Player = 2;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
